services:
    app.repository.problem:
        class: AppBundle\Entity\ProblemRepository
        factory: [@doctrine, getRepository]
    app.repository.project:
        class: AppBundle\Entity\ProjectRepository
        factory: [@doctrine, getRepository]
